export type Lang = "en" | "he";
export const LANG_COOKIE = "fl-lang";

const en = {
  skip: "Skip to content",
  previewBar: "Preview · site is in waitlist mode · only admins see the shop",
  navShop: "Shop",
  navAbout: "About",
  navLogin: "Log in",
  navAccount: "Account",
  navAdmin: "Admin",
  langSwitch: "עב",
  langSwitchLabel: "עברית",

  footerTag: "Lost & found",
  footerPrivacy: "Privacy",
  footerTerms: "Terms",
  footerA11yMenu: "Accessibility menu",
  footerA11yStatement: "Accessibility statement",

  tagline: "couldn't find clothes we liked, so we made them.",
  heroOpen: "Drop 001 is out",
  heroShop: "Shop the drop",
  heroSoon: "First drop soon",
  shopHead: "Drop 001 · {n} items",
  shopNote: "Preorder · pay with Bit or PayBox",
  shopLabel: "Shop",

  cdDays: "Days",
  cdHrs: "Hrs",
  cdMin: "Min",
  cdSec: "Sec",
  cdTba: "Drop 001 · Date TBA",
  cdNow: "Drop 001 · any minute now",
  cdLabel: "Time until the drop",

  signupCta: "Notify me",
  signupPlaceholder: "Your email",
  signupHint: "Join the list. Only drops, no spam.",
  signupDone: "You're on the list. First drop soon.",
  signupAlready: "You're already on the list.",
  errGeneric: "Something went wrong. Try again.",

  itemNo: "Item no.",
  soldOut: "Sold out",
  soldOutMsg: "This one is gone. Maybe it comes back.",
  sizes: "Sizes",
  front: "front",
  back: "back",
  alsoLike: "You may also like",

  preorder: "Preorder",
  preorderNote: "Made after you order. Pay with Bit (or PayBox), we send you the link.",
  size: "Size",
  name: "Name",
  phone: "Phone",
  email: "Email",
  note: "Note (optional)",
  oneEnough: "Phone or email, one is enough.",
  sending: "Sending...",
  noPayHere: "No payment here. We contact you with a Bit link (or PayBox) to pay.",
  orderDone: "Preorder #{id} received.",
  orderDoneBit: "We'll send a Bit payment link to {contact} soon (PayBox if you prefer). Payment confirms your preorder.",
  orderDoneMade: "This is a preorder: your piece is made after payment, we'll keep you posted on shipping.",
  agreeTerms: "By ordering you agree to the ",
  termsLink: "terms",
  andPrivacy: " and ",
  privacyLink: "privacy policy",

  errNoItem: "This item doesn't exist.",
  errSize: "Pick a size.",
  errContact: "Leave a phone number or an email so we can reach you.",
  errEmail: "That email doesn't look right.",
  errPhone: "That phone number looks too short.",
  errClosed: "Orders aren't open yet.",
  errSoldOut: "Sorry, this item is sold out.",
  errLogin: "Wrong email or password.",
  errPassword: "Password needs at least 8 characters.",
  errExists: "This email already has an account. Log in instead.",
  errSignup: "Couldn't create the account. Try again.",
  checkEmail: "Almost there. Check your email to confirm your account.",

  account: "Account",
  password: "Password",
  createAccount: "Create account",
  confirmFailed: "That confirmation link didn't work. Try logging in, or create the account again.",
  yourOrders: "Your orders",
  noOrders: "No orders yet.",
  logout: "Log out",
  stNew: "Received, waiting for Bit link",
  stContacted: "Bit link sent",
  stPaid: "Paid",
  stShipped: "On the way",
  stCancelled: "Cancelled",

  aboutTitle: "Lost & found",
  aboutP1: "We couldn't find clothes we liked, so we made them.",
  aboutP2: "Everything is preorder: pick your size, leave a phone or email, and we send you a link to pay with Bit (or PayBox).",

  nfTitle: "Lost? So are we.",
  nfBack: "Back to found",
};

export type Dict = typeof en;

const he: Dict = {
  skip: "דלג לתוכן",
  previewBar: "תצוגה מקדימה · האתר במצב רשימת המתנה · רק אדמינים רואים את החנות",
  navShop: "חנות",
  navAbout: "אודות",
  navLogin: "התחברות",
  navAccount: "החשבון שלי",
  navAdmin: "ניהול",
  langSwitch: "EN",
  langSwitchLabel: "English",

  footerTag: "Lost & found",
  footerPrivacy: "פרטיות",
  footerTerms: "תקנון",
  footerA11yMenu: "תפריט נגישות",
  footerA11yStatement: "הצהרת נגישות",

  tagline: "לא מצאנו בגדים שאהבנו, אז עשינו אותם.",
  heroOpen: "Drop 001 בחוץ",
  heroShop: "לקולקציה",
  heroSoon: "הדרופ הראשון בקרוב",
  shopHead: "Drop 001 · {n} פריטים",
  shopNote: "הזמנה מוקדמת · תשלום בביט או פייבוקס",
  shopLabel: "חנות",

  cdDays: "ימים",
  cdHrs: "שעות",
  cdMin: "דקות",
  cdSec: "שניות",
  cdTba: "Drop 001 · תאריך יפורסם",
  cdNow: "Drop 001 · עוד רגע",
  cdLabel: "זמן עד הדרופ",

  signupCta: "עדכנו אותי",
  signupPlaceholder: "האימייל שלך",
  signupHint: "רק דרופים, בלי ספאם.",
  signupDone: "נרשמת. הדרופ הראשון בקרוב.",
  signupAlready: "כבר נרשמת.",
  errGeneric: "משהו השתבש. נסו שוב.",

  itemNo: "מק״ט",
  soldOut: "אזל",
  soldOutMsg: "הפריט הזה נגמר. אולי הוא יחזור.",
  sizes: "מידות",
  front: "חזית",
  back: "גב",
  alsoLike: "אולי תאהבו גם",

  preorder: "הזמנה מוקדמת",
  preorderNote: "הפריט מיוצר אחרי ההזמנה. משלמים בביט (או פייבוקס), אנחנו שולחים לכם קישור.",
  size: "מידה",
  name: "שם",
  phone: "טלפון",
  email: "אימייל",
  note: "הערה (לא חובה)",
  oneEnough: "טלפון או אימייל, אחד מספיק.",
  sending: "שולח...",
  noPayHere: "אין תשלום כאן. נחזור אליכם עם קישור לתשלום בביט (או פייבוקס).",
  orderDone: "הזמנה מוקדמת #{id} התקבלה.",
  orderDoneBit: "נשלח קישור לתשלום בביט אל {contact} בקרוב (או פייבוקס אם נוח לכם). ההזמנה מאושרת אחרי התשלום.",
  orderDoneMade: "זו הזמנה מוקדמת: הפריט מיוצר אחרי התשלום, ונעדכן אתכם לגבי המשלוח.",
  agreeTerms: "בהזמנה אתם מסכימים ל",
  termsLink: "תקנון",
  andPrivacy: " ול",
  privacyLink: "מדיניות הפרטיות",

  errNoItem: "הפריט הזה לא קיים.",
  errSize: "בחרו מידה.",
  errContact: "השאירו טלפון או אימייל כדי שנוכל לחזור אליכם.",
  errEmail: "האימייל לא נראה תקין.",
  errPhone: "מספר הטלפון קצר מדי.",
  errClosed: "ההזמנות עוד לא נפתחו.",
  errSoldOut: "מצטערים, הפריט אזל.",
  errLogin: "אימייל או סיסמה שגויים.",
  errPassword: "הסיסמה צריכה לפחות 8 תווים.",
  errExists: "לאימייל הזה כבר יש חשבון. התחברו במקום.",
  errSignup: "לא הצלחנו ליצור חשבון. נסו שוב.",
  checkEmail: "כמעט שם. בדקו את האימייל כדי לאשר את החשבון.",

  account: "החשבון שלי",
  password: "סיסמה",
  createAccount: "יצירת חשבון",
  confirmFailed: "קישור האישור לא עבד. נסו להתחבר, או צרו את החשבון מחדש.",
  yourOrders: "ההזמנות שלך",
  noOrders: "עדיין אין הזמנות.",
  logout: "התנתקות",
  stNew: "התקבלה, מחכה לקישור ביט",
  stContacted: "נשלח קישור ביט",
  stPaid: "שולם",
  stShipped: "בדרך אליך",
  stCancelled: "בוטלה",

  aboutTitle: "Lost & found",
  aboutP1: "לא מצאנו בגדים שאהבנו, אז עשינו אותם.",
  aboutP2: "הכל בהזמנה מוקדמת: בוחרים מידה, משאירים טלפון או אימייל, ואנחנו שולחים קישור לתשלום בביט (או פייבוקס).",

  nfTitle: "הלכתם לאיבוד? גם אנחנו.",
  nfBack: "חזרה הביתה",
};

export const dicts: Record<Lang, Dict> = { en, he };

export function fill(s: string, vars: Record<string, string | number>) {
  return s.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));
}

